// Mocks generated by Mockito 5.4.4 from annotations
// in bab_news/test/features/top_stories/data/datasources/stories_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:bab_news/core/utils/enums.dart' as _i5;
import 'package:bab_news/features/top_stories/data/datasources/stories_data_source.dart'
    as _i2;
import 'package:bab_news/features/top_stories/domain/entities/story_entity.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [StoriesDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockStoriesDataSource extends _i1.Mock implements _i2.StoriesDataSource {
  @override
  _i3.Future<List<_i4.StoryEntity>?> getStories(_i5.StorySection? section) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStories,
          [section],
        ),
        returnValue: _i3.Future<List<_i4.StoryEntity>?>.value(),
        returnValueForMissingStub: _i3.Future<List<_i4.StoryEntity>?>.value(),
      ) as _i3.Future<List<_i4.StoryEntity>?>);
}
