// Mocks generated by Mockito 5.4.4 from annotations
// in bab_news/test/features/network/data/datasources/network_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:bab_news/features/network/data/datasources/network_data_source.dart'
    as _i2;
import 'package:dio/dio.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [NetworkDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkDataSource extends _i1.Mock implements _i2.NetworkDataSource {
  @override
  _i3.Future<Map<String, dynamic>?> getRequest({
    required String? apiPath,
    Map<String, dynamic>? extraHeaders,
    Function? onException,
    String? queryParameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRequest,
          [],
          {
            #apiPath: apiPath,
            #extraHeaders: extraHeaders,
            #onException: onException,
            #queryParameters: queryParameters,
          },
        ),
        returnValue: _i3.Future<Map<String, dynamic>?>.value(),
        returnValueForMissingStub: _i3.Future<Map<String, dynamic>?>.value(),
      ) as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<Map<String, dynamic>?> postRequest({
    required String? apiPath,
    Function? onException,
    Map<String, dynamic>? extraHeaders,
    Map<String, dynamic>? requestBody,
    Function? onSendProgress,
    _i4.FormData? formData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postRequest,
          [],
          {
            #apiPath: apiPath,
            #onException: onException,
            #extraHeaders: extraHeaders,
            #requestBody: requestBody,
            #onSendProgress: onSendProgress,
            #formData: formData,
          },
        ),
        returnValue: _i3.Future<Map<String, dynamic>?>.value(),
        returnValueForMissingStub: _i3.Future<Map<String, dynamic>?>.value(),
      ) as _i3.Future<Map<String, dynamic>?>);
}
